services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: gym
      POSTGRES_USER: abs
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5440:5432"
    networks:
      - gym

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=host=db user=abs password=yourpassword dbname=gym port=5432 sslmode=disable TimeZone=UTC
      - JWT_SECRET=supersecret
    networks:
      - gym

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - gym

volumes:
  postgres_data:

networks:
  gym:
